apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test 
  
resources:
- ../../bases

images:
- name: vfondevilla/revolut-test
  newName: vfondevilla/revolut-prod
  newTag: production

patches:
- target:
    kind: StatefulSet
    name: redis
  patch: |-
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/storageClassName
      value: gp2